name: Auto Add Issue to Project
on:
issues:
types: [opened]


jobs:
add-to-project:
runs-on: ubuntu-latest
permissions:
issues: read
repository-projects: write
contents: read
steps:
- name: Add to Project
uses: actions/add-to-project@v0.5.0
with:
project-url: https://github.com/aptma-sHEWTeam/HEW_ECS
github-token: ${{ secrets.GITHUB_TOKEN }}