name: Auto Update Status to Done

on:
  issues:
    types: [closed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set Status to Done
        uses: leonsteinhaeuser/project-beta-automations@v1
        with:
          project-url: https://github.com/orgs/aptma-sHEWTeam/projects/3
          field: Status
          value: Done
          gh-token: ${{ secrets.ORG_PROJECTS_TOKEN }}          gh-token: ${{ secrets.ORG_PROJECTS_TOKEN }}