---
name: Auto Update Status to Done

'on':
  issues:
    types: [closed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set Status to Done (GraphQL)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PROJECTS_TOKEN }}
          script: |
            const org = 'aptma-sHEWTeam';
            const projectNumber = 3;
            const doneNames = ['Done','完了'].map(s=>s.toLowerCase());
            const issue = context.payload.issue;
            if (!issue) throw new Error('This workflow only runs on issues');

            const fieldsQuery = `
              query($org: String!, $number: Int!) {
                organization(login: $org) {
                  projectV2(number: $number) {
                    id
                    fields(first: 50) {
                      nodes {
                        ... on ProjectV2Field { id name dataType }
                        ... on ProjectV2SingleSelectField { id name dataType options { id name } }
                      }
                    }
                  }
                }
              }
            `;

            const pageQuery = `
              query($org: String!, $number: Int!, $first: Int!, $after: String) {
                organization(login: $org) {
                  projectV2(number: $number) {
                    items(first: $first, after: $after) {
                      nodes { id content { ... on Issue { id number } } }
                      pageInfo { hasNextPage endCursor }
                    }
                  }
                }
              }
            `;

            const addMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: { projectId: $projectId, contentId: $contentId }) { item { id } }
              }
            `;

            const updateMutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: ID!) {
                updateProjectV2ItemFieldValue(input: { projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: { singleSelectOptionId: $optionId } }) { projectV2Item { id } }
              }
            `;

            // 1) Project + fields
            const fieldsRes = await github.graphql(fieldsQuery, { org, number: projectNumber });
            const project = fieldsRes.organization.projectV2;
            const projectId = project.id;
            // Prefer SINGLE_SELECT field named Status/ステータス
            const statusField = project.fields.nodes.find(f =>
              (f.name && (f.name.trim().toLowerCase() === 'status' || f.name.trim() === 'ステータス')) &&
              (f.dataType === 'SINGLE_SELECT')
            );
            if (!statusField) throw new Error('Status (single-select) field not found');
            const options = (statusField.options || []).map(o=>({name:o.name,id:o.id}));
            const optIdByName = new Map(options.map(o=>[o.name.trim().toLowerCase(), o.id]));
            let doneOptionId = null;
            for (const n of doneNames) { if (optIdByName.has(n)) { doneOptionId = optIdByName.get(n); break; } }
            if (!doneOptionId) throw new Error('Done option not found. Available: ' + options.map(o=>o.name).join(', '));

            // 2) Find item (paged)
            async function findItemId() {
              let after = null;
              while (true) {
                const res = await github.graphql(pageQuery, { org, number: projectNumber, first: 100, after });
                const items = res.organization.projectV2.items;
                const hit = items.nodes.find(n => n.content && n.content.number === issue.number);
                if (hit) return hit.id;
                if (!items.pageInfo.hasNextPage) return null;
                after = items.pageInfo.endCursor;
              }
            }

            let itemId = await findItemId();
            if (!itemId) {
              try {
                const addRes = await github.graphql(addMutation, { projectId, contentId: issue.node_id });
                itemId = addRes.addProjectV2ItemById.item.id;
              } catch (e) {
                // ignore, fall back to lookup
              }
              if (!itemId) itemId = await findItemId();
            }
            if (!itemId) throw new Error('Project item for this issue not found');

            // 3) Update status to Done
            await github.graphql(updateMutation, { projectId, itemId, fieldId: statusField.id, optionId: doneOptionId });
            console.log('Status set to Done for item', itemId);